site_name: My Docs
theme:
  name: 'material'
nav:
  - Home: index.md
  - UI/UX:
    - Một website tốt trên mobile là như thế nào: ui-ux/mot-website-tot-tren-mobile-la-nhu-the-nao.md
    - Focus: ui-ux/focus.md
  - Security:
    - Content Security Policy: security/content-security-policy.md
    - Tại sao cần HTTPs: security/tai-sao-can-https.md
    - Những thuật ngữ bảo mật quan trọng: security/thuat-ngu-bao-mat-quan-trong.md
