site_name: Kiến thức nền tảng của Web
theme:
  name: 'material'
  highlightjs: true
nav:
  - Home: index.md
  - Thuật ngữ: thuat-ngu.md
  - UI/UX:
    - Font chữ trên web: ui-ux/font.md
    - Một website tốt trên mobile là như thế nào: ui-ux/mot-website-tot-tren-mobile-la-nhu-the-nao.md
    - Focus: ui-ux/focus.md
    - DOM Order: ui-ux/dom-order.md
    - Tab Index: ui-ux/su-dung-tab-index.md
    - Aria: ui-ux/aria.md
    - SEO: ui-ux/seo.md
    - Hiding update content: ui-ux/hiding-update-content.md
    - Layout responsive: ui-ux/responsive-pattern.md
    - Responsive image: ui-ux/responsive-image.md
    - Thêm nút Add to Homescreen: ui-ux/add-to-homescreen.md
    - Gợi ý cài đặt PWA: ui-ux/install-pwa.md
  - Tương tác:
    - Thêm touch cho website: interact/touch.md
    - Thiết kế form thật ngầu: interact/form.md
    - Lấy thông tin vị trí của user: interact/user-location.md
    - Web App Manifest: interact/web-app-manifest.md
    - Tương tác với mạng xã hội: interact/mang-xa-hoi.md
  - Security:
    - Những thuật ngữ bảo mật quan trọng: security/thuat-ngu-bao-mat-quan-trong.md
    - Phân biệt same site và same origin: security/phan-biet-same-site-same-origin.md
    - Content Security Policy: security/content-security-policy.md
    - Phòng tránh XSS bằng CSP: security/bao-ve-xss-bang-content-security-policy.md
    - Phòng tránh XSS bằng Trusted Type: security/phong-tranh-dom-xss-voi-trusted-type.md
    - Tại sao cần HTTPs: security/tai-sao-can-https.md
    - Mixed content là gì: security/mixed-content-la-gi.md
    - Sử dụng HTTPS ở localhost: security/khi-nao-dung-https-o-localhost.md
  - Audit:
    - Giới thiệu: audit/overview.md
    - Kiểm tra bảo mật: audit/check-site-security.md
    - Công cụ đánh giá: audit/cong-cu-danh-gia.md
    - Kiểm tra tốc độ:
      - Hệ thống đánh giá của Lighthouse: audit/he-thong-danh-gia-lighthouse.md
      - First Contentful Paint: audit/first-contentful-paint.md
      - Speed Index: audit/speed-index.md
      - Time to interactive: audit/time-to-interactive.md
      - Max Potential First Input Delay: audit/thoi-gian-input-cham-nhat.md
      - Total Blocking Time: audit/total-blocking-time.md
      - Largest Contentful Paint: audit/largest-contentful-paint.md
    - Cải thiện tốc độ:
      - Xóa resource render blocking: audit/xoa-resource-render-blocking.md
      - Lazy load third-party resource với facade: audit/lazy-load-third-party-resource-voi-facade.md
      - Infinite scroll không bị layout shift: audit/infinite-scroll-khong-bi-layout-shift.md
      - Sử dụng preconnect origin: audit/su-dung-preconnect-origin.md
  - Best practice:
    - Cải thiện first input delay: base/cai-thien-first-input-delay.md
    - Debug layout shift: base/debug-layout-shift.md
    - HTML không có doctype: base/html-khong-co-doctype.md
    - Largest Contentful Paint: base/largest-contentful-paint.md
    - Sử dụng passive listener: base/su-dung-passive-listener-de-cai-thien-hieu-nang-khi-scroll.md
  - Kỹ thuật nền tảng:
    - Mô hình vỏ ứng dụng: base/app-shell.md
    - Hàm async: base/async.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/hybrid.min.css

