site_name: Kiến thức nền tảng của Web
theme:
  name: 'material'
nav:
  - Home: index.md
  - UI/UX:
    - Font chữ trên web: ui-ux/font.md
    - Một website tốt trên mobile là như thế nào: ui-ux/mot-website-tot-tren-mobile-la-nhu-the-nao.md
    - Focus: ui-ux/focus.md
    - DOM Order: ui-ux/dom-order.md
    - Tab Index: ui-ux/su-dung-tab-index.md
    - Aria: ui-ux/aria.md
    - SEO: ui-ux/seo.md
    - Hiding update content: ui-ux/hiding-update-content.md
    - Layout responsive: ui-ux/responsive-pattern.md
    - Responsive image: ui-ux/responsive-image.md
  - Tương tác:
    - Thêm touch cho website: interact/touch.md
    - Thiết kế form thật ngầu: interact/form.md
  - Security:
    - Content Security Policy: security/content-security-policy.md
    - Tại sao cần HTTPs: security/tai-sao-can-https.md
    - Những thuật ngữ bảo mật quan trọng: security/thuat-ngu-bao-mat-quan-trong.md
    - Mixed content là gì: security/mixed-content-la-gi.md
  - Audit:
    - Giới thiệu: audit/overview.md
    - Kiểm tra bảo mật: audit/check-site-security.md
    - Công cụ đánh giá: audit/cong-cu-danh-gia.md
  - Kỹ thuật nền tảng:
    - Hàm async: base/async.md
markdown_extensions:
  - codehilite
